version: "3.9"
services:
  web:
    build: .
    container_name: web
    environment:
      DB_IP: "${DB_IP}"
      DB_USER: "${DB_USER}"
      DB_PASS: "${DB_PASS}"
      DB_AUTH: "${DB_AUTH}"
    ports:
      - 80:5000
    restart: always
    volumes:
      - type: bind
        source: ./logs
        target: /app/logs
